package com.ganecamp.domain.enums

enum class AuthRespond {
    OK, USER_NOT_FOUND, EMAIL_ALREADY_IN_USE, INVALID_EMAIL, WEAK_PASSWORD, TOKEN_NOT_FOUND, FARM_NOT_FOUND, USER_DISABLED, NETWORK_ERROR, UNKNOWN_ERROR, UNEXPECTED, GETTING_USER_INFO, USER_NOT_CREATED, REGISTERING_USER
}