package com.ganecamp.domain.enums

enum class ErrorType {
    CANCELLED,
    INVALID_ARGUMENT,
    NOT_FOUND,
    PERMISSION_DENIED,
    UNAUTHENTICATED,
    ABORTED,
    ALREADY_EXISTS,
    FAILED_PRECONDITION,
    OUT_OF_RANGE,
    UNAVAILABLE,
    DATA_LOSS,
    UNKNOWN,
    UNEXPECTED,
    NULL_POINTER,
    NO_FARM_SESSION,
    USER_NOT_FOUND,
    EMAIL_ALREADY_IN_USE,
    INVALID_EMAIL,
    USER_DISABLED,

}