package com.ganecamp.domain.enums

enum class RepositoryRespond {
    OK, CANCELLED, INVALID_ARGUMENT, NOT_FOUND, PERMISSION_DENIED, UNAUTHENTICATED, ABORTED, ALREADY_EXISTS, FAILED_PRECONDITION, OUT_OF_RANGE, UNAVAILABLE, DATA_LOSS, UNKNOWN, UNEXPECTED, NULL_POINTER, NO_FARM_SESSION
}